version: "3.3"
services:
  # Setup the runner
  # we need to set the localhost and root password as they can be different
  crawler:
    image: ghcr.io/sanger/crawler/crawler:1.28.0-1516149682-develop
    ports:
      - "8100:8000"
    environment:
      - LOCALHOST=host.docker.internal
      - ROOT_PASSWORD=
      - SETTINGS_MODULE=crawler.config.development

    volumes:
      - ".:/code"

    networks:
      - default
      - heron_databases_external

networks:
  heron_databases_external:
    external: true
