# mongo collections
COLLECTION_CENTRES = "centres"
COLLECTION_IMPORTS = "imports"
COLLECTION_SAMPLES = "samples"
COLLECTION_SAMPLES_HISTORY = "samples_history"

# field names
FIELD_PLATE_BARCODE = "plate_barcode"
FIELD_CENTRE_NAME = "name"
FIELD_COORDINATE = "coordinate"
FIELD_DATE_TESTED = "Date Tested"
FIELD_LAB_ID = "Lab ID"
FIELD_RESULT = "Result"
FIELD_RNA_ID = "RNA ID"
FIELD_ROOT_SAMPLE_ID = "Root Sample ID"
FIELD_LINE_NUMBER = "line_number"
FIELD_FILE_NAME = "file_name"
FIELD_FILE_NAME_DATE = "file_name_date"
FIELD_CREATED_AT = "_created"
FIELD_UPDATED_AT = "_updated"
