# Checks that the .release-version file has been updated
name: Check release version

on:
  pull_request:
    branches:
      - master

jobs:
  check-release-verion:
    uses: sanger/.github/.github/workflows/check-release-version.yml@master
