name: Docker - build, test and push

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    tags:
      - v*

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_test_push:
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo:4.2.5
        ports:
          - 27017:27017

      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: null
          MYSQL_DATABASE: unified_warehouse_test
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}

      - name: Create mysql test warehouse database and table
        run: >-
          docker run
          --network host
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
          python setup_test_db.py

      - name: Run tests against the image
        run: >-
          docker run
          --network host
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
          python -m  pytest --no-cov -vx

      - name: Login to registry
        if: ${{ github.event_name == 'push' }}
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com

      - name: Publish image with image tag being either develop/master/<tag_name>
        if: ${{ github.event_name == 'push' }}
        run: >-
          docker push
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
